### ISSUE TITLE
websockets

### ISSUE THREAD

**Issue by kostja** [tarantool/http#8]
Support websocket protocol

**Comment by aleclarson** [comment]
Does https://github.com/lipp/lua-websockets work in the meantime (as a websocket client)?

**Comment by racktear** [comment]
I don't think it's possible without a major refactoring of the http server

**Comment by aleclarson** [comment]
@racktear I'd be happy with only a websocket client to start, but I can understand why you'd want to add both client/server at same time.

@bigbes said [client_sync.lua][1] and [server_ev.lua][2] would be good candidates for refactoring. Then we could send a pull request that adds `client_tarantool.lua` and `server_tarantool.lua` to the project.

[1]: https://github.com/lipp/lua-websockets/blob/master/src/websocket/client_sync.lua
[2]: https://github.com/lipp/lua-websockets/blob/master/src/websocket/server_ev.lua

**Comment by racktear** [comment]
@aleclarson having websocket client in this module is mostly useless, as it won't support SSL. Websocket server will even be easier to add because of abundant reverse-proxies.

We now have libcurl-based http client in tarantool 1.7, that supports SSL, but since websockets are different, to add support for them we'd need to hand-roll our own http client state machine.

Having said that, I don't see this as something impossible. My own opinion is that websocket server library will be useful. However, I don't see many viable use-cases for the client library. Can you please share your use-cases?

**Comment by nk-1** [comment]
@racktear it might be used for microservice communication.

**Comment by rybakit** [comment]
> My own opinion is that websocket server library will be useful. However, I don't see many viable use-cases for the client library.

:+1: I personally would like to see websocket server being implemented and don't care about the client library.

**Comment by racktear** [comment]
I've recently come across https://github.com/daurnimator/lua-http, and at first I was skeptical, because most of the third-party socket-based stuff doesn't work well with Tarantool event loop. But people report that lua-http works fine. If this is really the case, it may be reasonable to just ditch this http server in favor of lua-http, which has SSL and websockets onboard.

**Comment by nk-1** [comment]
https://github.com/tarantool/tarantool/issues/1203 it'd be also nice to link it to pub/sub

**Comment by aleclarson** [comment]
This gist serves as a guide for using https://github.com/daurnimator/lua-http in tandem with Tarantool; both as an HTTP server and WebSocket server: 

https://gist.github.com/daurnimator/f1c7965b47a5658b88300403645541aa

I'm in favor of deprecating this repo, so the Tarantool team has more time to dedicate to other development.

**Comment by filonenko-mikhail** [comment]
solved
https://github.com/tarantool/websocket
